name: Build_SpaceXit_V4_Ghost

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "~/theos/bin" >> $GITHUB_PATH

      - name: Baixar SDK iOS (Link Alternativo Direto)
        run: |
          mkdir -p ~/theos/sdks
          # Usando o mirror do xybp888 que é específico para builds de Actions
          curl -L "https://github.com/xybp888/iOS-SDKs/raw/master/iPhoneOS14.5.sdk.tar.xz" -o ~/theos/sdks/sdk.tar.xz
          cd ~/theos/sdks
          tar -xJf sdk.tar.xz
          rm sdk.tar.xz

      - name: Compilar Dylib (Modo Stealth)
        run: |
          export THEOS=~/theos
          export PATH="$THEOS/bin:$PATH"
          # Adicionamos o comando para dar permissão de execução ao executável do Theos
          chmod +x $THEOS/bin/nic.pl
          make package FINALPACKAGE=1
          
      - name: Upload da Dylib Pronta
        uses: actions/upload-artifact@v4
        with:
          name: SpaceXit_V4_Bypass_Final
          path: packages/*.deb
