name: Build_SpaceXit_V4_Ghost

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "~/theos/bin" >> $GITHUB_PATH

      - name: Baixar SDK iOS (Correção Exit Code 128)
        run: |
          # Remove a pasta sdks vazia que o Theos criou para evitar erro 128
          rm -rf ~/theos/sdks
          # Clona os SDKs de forma limpa
          git clone --depth 1 https://github.com/theos/sdks.git ~/theos/sdks

      - name: Compilar Dylib (Modo Stealth)
        run: |
          export THEOS=~/theos
          export PATH="$THEOS/bin:$PATH"
          # Comando para compilar
          make package FINALPACKAGE=1
          
      - name: Upload da Dylib Pronta
        uses: actions/upload-artifact@v4
        with:
          name: SpaceXit_V4_Bypass_Final
          path: packages/*.deb
