name: Build_SpaceXit_V4_Ghost

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar Theos Manual
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "~/theos/bin" >> $GITHUB_PATH

      - name: Baixar SDK iOS (Correção de Formato)
        run: |
          mkdir -p ~/theos/sdks
          # Usando um link alternativo mais estável para o SDK 14.5
          curl -L "https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz" -o ~/theos/sdks/sdk.tar.xz
          cd ~/theos/sdks
          tar -xJf sdk.tar.xz
          rm sdk.tar.xz

      - name: Compilar Dylib (Modo Stealth)
        run: |
          # Define as variáveis de ambiente diretamente no comando para não ter erro
          export THEOS=~/theos
          export PATH="$THEOS/bin:$PATH"
          make package FINALPACKAGE=1
          
      - name: Upload da Dylib Pronta
        uses: actions/upload-artifact@v4
        with:
          name: SpaceXit_V4_Bypass_Final
          path: packages/*.deb
